src/Entity/Culture.php
<?php

namespace App\Entity;

use App\Repository\CultureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ProxyManager\ProxyGenerator\ValueHolder\MethodGenerator\Constructor;
use Symfony\Component\Validator\Constraints as Assert;
use symfony\Component\Serializer\Annotation\Groups;
#[ORM\Entity(repositoryClass: CultureRepository::class)]
class Culture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("culture")]
    private ?int $id = null;
    #[Assert\NotBlank(message:"ce champ est obligatoire")]
    #[Assert\Type(
        type: 'string',
        message: 'le type {{ value }} n est pas valide {{ type }}.',)]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'donner le type au moins {{ limit }} caractères ',
        maxMessage: 'donner le type maximum {{ limit }} caractères',)]
    #[ORM\Column(length: 255)]
    #[Groups("culture")]
    private ?string $type = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("culture")]
    #[Assert\NotNull(message:"ce champ est obligatoire")]
    private ?\DateTimeInterface $date_planting = null;
    // #[Assert\NotBlank]
    #[Assert\NotBlank(message:"ce champ est obligatoire")]
    #[Assert\Type(
        type: 'float',
        message: 'la quantité {{ value }} nest pas valide {{ type }}.',)]

    #[ORM\Column]
    #[Groups("culture")]
    private ?float $quantite = null;

    #[Assert\NotBlank(message:"ce champ est obligatoire")]
    #[Groups("culture")]
    #[ORM\OneToMany(mappedBy: 'culture', targetEntity: Terrain::class)]
    private Collection $terrain;

    public function __construct()
    {

        $this->terrain = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDatePlanting(): ?\DateTimeInterface
    {
        return $this->date_planting;
    }

    public function setDatePlanting(\DateTimeInterface $date_planting): self
    {
        $this->date_planting = $date_planting;

        return $this;
    }

    public function getQuantite(): ?float
    {
        return $this->quantite;
    }

    public function setQuantite(float $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    /**
     * @return Collection<int, Terrain>
     */
    public function getTerrain(): Collection
    {
        return $this->terrain;
    }

    public function addTerrain(Terrain $terrain): self
    {
        if (!$this->terrain->contains($terrain)) {
            $this->terrain->add($terrain);
            $terrain->setCulture($this);
        }

        return $this;
    }

    public function removeTerrain(Terrain $terrain): self
    {
        if ($this->terrain->removeElement($terrain)) {
            // set the owning side to null (unless already changed)
            if ($terrain->getCulture() === $this) {
                $terrain->setCulture(null);
            }
        }

        return $this;
    }
    public function __toString():string
    {
        return $this->type." ".$this->quantite;
    }
}

src/Form/CultureType.php
<?php

namespace App\Form;

use App\Entity\Culture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

use Symfony\Component\Validator\Constraints\LessThanOrEqual;

class CultureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', TextType::class, [
                'constraints' => [
                    new LessThanOrEqual([
                        'value' => 'today',
                        'message' => 'The date must be less than or equal to today\'s date.'
                    ])
                ],
            ],)
            // ->add('date_planting',DateType::class)
            ->add ('date_planting', DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'empty_data' => null,
                'constraints' => [
                    new LessThanOrEqual([
                        'value' => 'today',
                        'message' => 'il faut ajouter une date precise avant ce jour  '],)], ],)
            ->add('quantite',NumberType::class , array(
                'scale' => 2,
                'attr' => array(
                    'placeholder' => '0.00'),
                'invalid_message' => 'la quantité doit être un nombre.'))
            ->add('ajouter',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Culture::class,
        ]);
    }
}

src/Controller/CultureController.php
<?php

namespace App\Controller;


use Dompdf\Dompdf;
use App\Entity\Culture;
use App\Form\CultureType;
use App\Repository\CultureRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[Route('/cultures')]
class CultureController extends AbstractController
{

    #[Route("/culture/calendar", name: "culture_calendar")]
    public function calendar(): JsonResponse
    {
        // retrieve all the events related to the Culture entity
        $cultures = $this->getDoctrine()->getRepository(Culture::class)->findAll();

        // format the events data in the required format by FullCalendar, which is JSON
        $events = [];
        foreach ($cultures as $culture) {
            $events[] = [
                'title' => $culture->getType(),
                'start' => $culture->getDatePlanting()->format('Y-m-d'),
            ];
        }

        // send the events data in JSON format
        return $this->json($events);
    }
    #[Route('/generate-pdf', name: 'app_culture_generate_pdf')]
    public function generatePdf(CultureRepository $cultureRepository): Response
    {
        // Fetch the cultures from the repository
        $cultures = $cultureRepository->findAll();

        // Render the cultures into HTML using a template
        $html = $this->renderView('culture/pdf.html.twig', [
            'cultures' => $cultures,
        ]);

        // Use Dompdf to generate a PDF from the HTML
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // Output the generated PDF to the browser
        $response = new Response($dompdf->output());
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'attachment;filename="cultures.pdf"');

        return $response;
    }

    #[Route('/all', name: 'app_culture_index')]

    public function pag(Request $request, CultureRepository $cultureRepository, PaginatorInterface $paginator): Response
    {
        $query = $cultureRepository->createQueryBuilder('c') // Use query builder to create a query
        ->orderBy('c.type', 'DESC') // Sort by ID in descending order
        ->getQuery(); // Get the query object

        $cultures = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            1
        );
        return $this->render('culture/pg.html.twig', [
            'culture' => $cultures,
        ]);
    }

    #[Route('/stats', name: 'app_culture_stats', methods: ['GET'])]
    public function stat(CultureRepository $cultureRepository): Response
    {
        $cultures = $cultureRepository->findAll();
        $cultureCounts = [];

        foreach ($cultures as $culture) {
            $cultureName = $culture->getType();
            if (!array_key_exists($cultureName, $cultureCounts)) {
                $cultureCounts[$cultureName] = 0;
            }
            $cultureCounts[$cultureName]++;
        }

        return $this->render('culture/stats.html.twig', [
            'cultureCounts' => $cultureCounts,
        ]);
    }

    #[Route('/new', name: 'app_culture_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CultureRepository $cultureRepository): Response
    {
        $culture = new Culture();
        $form = $this->createForm(CultureType::class, $culture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $cultureRepository->save($culture, true);


            return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('culture/new.html.twig', [
            'culture' => $culture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_culture_show', methods: ['GET'])]
    public function show(Culture $culture): Response
    {
        return $this->render('culture/show.html.twig', [
            'culture' => $culture,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_culture_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Culture $culture, CultureRepository $cultureRepository): Response
    {
        $form = $this->createForm(CultureType::class, $culture);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $cultureRepository->save($culture, true);



            return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('culture/edit.html.twig', [
            'culture' => $culture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_culture_delete', methods: ['POST'])]
    public function delete(Request $request, Culture $culture,CultureRepository $cultureRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$culture->getId(), $request->request->get('_token'))) {
            $relatedEntities = $culture->getTerrain();
            if ($relatedEntities->count() > 0) {
                return new Response('Cette culture ne peut pas être supprimée car elle est liée à un ou plusieurs terrains');
            }
            $cultureRepository->remove($culture, true);

        }
        return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route("/liste", name: "liste")]
    public function getCulture(CultureRepository $cultureRepository,SerializerInterface $serializer)
    {

        $culture=$cultureRepository->findAll();
        $json =$serializer->serialize($culture, 'json', ['groups'=>"culture"]);
        return new Response($json);
    }
    #[Route("addculture/new", name: "addculture")]
    public function addCulture(Request $req,NormalizerInterface $Normalizer)
    {

        $em = $this->getDoctrine()->getManager();
        $culture = new culture();
        $culture->setDatePlanting($req->get('date'));
        $culture->setType($req->get('type'));
        $em->persist($culture);
        $em->flush();

        $jsonContent = $Normalizer->normalize($culture, 'json', ['groups' => '$culture']);
        return new Response(json_encode($jsonContent));
    }
    #[Route("/showculture/{id}", name: "showculture")]
    public function showculture($id, NormalizerInterface $normalizer, CultureRepository $cultureRepository)
    {
        $culture = $cultureRepository->find($id);

        $cultureNormalise = $normalizer->normalize($culture, 'json', ['groups' => "culture"]);
        return new Response(json_encode($cultureNormalise));
    }
    #[Route("/deleteculture/{id}", name: "deleteculture")]
    public function deleteculture(Request $req, $id, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $culture = $em->getRepository(culture::class)->find($id);
        $em->remove($culture);
        $em->flush();
        $jsonContent = $Normalizer->normalize($culture, 'json', ['groups' => 'culture']);
        return new Response( json_encode($jsonContent));
    }
}

templates/culture/_delete_form.html.twig
<form method="post" action="{{ path('app_culture_delete', {'id': culture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ culture.id) }}">
    <button class="btn">Delete</button>
</form>

templates/culture/_form.html.twig
{{ form_start(form) }}

<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/culture/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Edit Culture</h1>
    <div class="row">
        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 20px; padding: 10px;">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"> modifier </h5>
                    {{ form_start(form) }}
                    <p>
                        <label for="inputText" class="col-sm-4 col-form-label">type</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.type,{'attr':{'class':'form-control'}}) }}
                    </div>
                    </p>
                    <p>
                        <label for="Text" class="col-sm-4 col-form-label">date_plantation</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.date_planting,{'attr':{'class':'form-control'}}) }}

                    </div>
                    </p>
                    <p>
                        <label for="inputText" class="col-sm-4 col-form-label">quantité</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.quantite,{'attr':{'class':'form-control'}}) }}
                    </div>
                    </p>

                    {{ form_end(form) }}

                </div>
            </div>

        </div>

    </div>

{% endblock %}

templates/culture/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
    <h1>Culture index</h1>
    <div class="card">
        <div class="card-header">
            <a class="btn btn-outline-primary" href="{{ path('app_culture_new') }} ">
                une nouvelle culture
            </a>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Type</th>
                    <th>date_plantation</th>
                    <th>Quantité</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for culture in cultures %}
                    <tr>
                        <td>{{ culture.id }}</td>
                        <td>{{ culture.type }}</td>
                        <td>{{ culture.datePlanting ? culture.datePlanting|date('Y-m-d') : '' }}</td>
                        <td>{{ culture.quantite }}</td>
                        <td>
                            <a class="btn btn-outline-info" href="{{ path('app_culture_show', {'id': culture.id}) }}">afficher</a>
                            <a class="btn btn-outline-success" href="{{ path('app_culture_edit', {'id': culture.id}) }}">modifier</a>
                            <a class="btn btn-outline-success" href="{{ path('app_culture_delete', {'id': culture.id}) }}">supprimer</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <a class="btn btn-outline-info"  href="{{ path('app_culture_generate_pdf') }}">PDF</a>
            <a class="btn btn-outline-success"  href="{{ path('app_culture_stats')}}">stat</a>
        </div>
    </div>


{% endblock %}

templates/culture/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="row">


        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Ajouter Culture </h5>

                <!-- General Form Elements -->

                {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}

                <label for="inputText" class="col-sm-4 col-form-label">type</label>
                <div class="col-sm-20">
                    {{ form_widget(form.type,{'attr':{'class':'form-control'}}) }}

                </div>
                {{ form_errors(form.type,{'attr':{'class':'text-danger'}}) }}


                <label for="inputText" class="col-sm-4 col-form-label">date_plantation</label>
                <div class="col-sm-20">
                    {{ form_widget(form.date_planting,{'attr':{'class':'form-control'}}) }}

                </div>
                {{ form_errors(form.date_planting,{'attr':{'class':'text-danger'}}) }}


                <p>
                    {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                    <label for="inputText" class="col-sm-4 col-form-label">quantité</label>
                <div class="col-sm-20">
                    {{ form_widget(form.quantite,{'attr':{'class':'form-control'}}) }}

                </div>
                {{ form_errors(form.quantite,{'attr':{'class':'text-danger'}}) }}

                </p>
                {{ form_end(form) }}


            </div>

        </div>

    </div>


{% endblock %}

templates/culture/pdf.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Culture Report</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            text-align: left;
            padding: 8px;
            border: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
<h1>Culture Report</h1>
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Type</th>
        <th>Date plantation</th>
        <th>Quantité</th>

    </tr>
    </thead>
    <tbody>
    {% for culture in cultures %}
        <tr>
            <td>{{ culture.id }}</td>
            <td>{{ culture.type }}</td>
            <td>{{ culture.datePlanting ? culture.datePlanting|date('Y-m-d') : '' }}</td>
            <td>{{ culture.quantite }}</td>
        </tr>

    {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/culture/pg.html.twig
{% extends 'base.html.twig' %}

{% block title %}Culture index{% endblock %}

{% block body %}
    <main style="text-align: center;">
        <div class="container">
            <h1>Culture index</h1>
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-outline-primary" href="{{ path('app_culture_new') }}">
                        une nouvelle culture
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th>Date plantation</th>
                            <th>Quantité</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for c in culture %}
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.type }}</td>
                                <td>{{ c.datePlanting ? c.datePlanting|date('Y-m-d') : '' }}</td>
                                <td>{{ c.quantite }}</td>
                                <td>
                                    <a class="btn btn-outline-info" href="{{ path('app_culture_show', {'id': c.id}) }}">Afficher</a>
                                    <a class="btn btn-outline-success" href="{{ path('app_culture_edit', {'id': c.id}) }}">Modifier</a>
                                    <a class="btn btn-outline-danger" href="{{ path('app_culture_delete', {'id': c.id}) }}">Supprimer</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">No records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <a class="btn btn-outline-success" href="{{ path('app_culture_stats') }}">Stats</a>
                    {{ knp_pagination_render(culture) }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/culture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Culture{% endblock %}

{% block body %}
    <h1>Culture</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ culture.id }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ culture.type }}</td>
        </tr>
        <tr>
            <th>date_plantation</th>
            <td>{{ culture.datePlanting ? culture.datePlanting|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Quantité</th>
            <td>{{ culture.quantite }}</td>
        </tr>
        </tbody>
    </table>

    <a class="btn btn-outline-success" href="{{ path('app_culture_index') }}">back to list</a>
    <a class="btn btn-outline-success" href="{{ path('app_culture_edit', {'id': culture.id}) }}">edit</a>

    {{ include('culture/_delete_form.html.twig') }}
{% endblock %}

templates/culture/stats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Culture Statistics{% endblock %}

{% block body %}
    <h1>Culture Statistics</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Culture</th>
            <th>Count</th>
        </tr>
        </thead>
        <tbody>
        {% for culture, count in cultureCounts %}
            <tr>
                <td>{{ culture }}</td>
                <td>{{ count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}